name: Release

on:
  push:
    branches: ["main"]
    tags:
      - "*"

jobs:
  release:
    permissions:
      # grant the github token the ability to modify release tags
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run Go Release
      run: |
        mkdir spin-plugin-terminal-darwin-arm64
        echo "echo 'spin-plugin-terminal-darwin-arm64 $(date)'" >> spin-plugin-terminal-darwin-arm64/terminal
        cd spin-plugin-terminal-darwin-arm64 && tar -czvf ../spin-plugin-terminal-darwin-arm64.tar.gz terminal && cd -

        mkdir spin-plugin-terminal-darwin-amd64
        echo "echo 'spin-plugin-terminal-darwin-amd64 $(date)'" >> spin-plugin-terminal-darwin-amd64/terminal
        cd spin-plugin-terminal-darwin-amd64 && tar -czvf ../spin-plugin-terminal-darwin-amd64.tar.gz terminal && cd -

        mkdir spin-plugin-terminal-linux-amd64
        echo "echo 'spin-plugin-terminal-linux-amd64 $(date)'" >> spin-plugin-terminal-linux-amd64/terminal
        cd spin-plugin-terminal-linux-amd64 && tar -czvf ../spin-plugin-terminal-linux-amd64.tar.gz terminal && cd -

        mkdir spin-plugin-terminal-linux-arm64
        echo "echo 'spin-plugin-terminal-linux-arm64 $(date)'" >> spin-plugin-terminal-linux-arm64/terminal
        cd spin-plugin-terminal-linux-arm64 && tar -czvf ../spin-plugin-terminal-linux-arm64.tar.gz terminal && cd -

      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload assets
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG=`echo ${GITHUB_REF} | sed 's/refs\/tags\///g'`
        echo $TAG
        gh release upload $TAG *.tar.gz --clobber
        gh release delete-asset $TAG terminal.json -y || true
        gh release delete-asset $TAG checksums.txt -y || true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Release Plugin
      if: startsWith(github.ref, 'refs/tags/')
      uses: rajatjindal/spin-plugin-releaser@v1
      with:
        github_token: ${{ github.token }}
        upload_checksums: true
        template_file: contrib/spin-plugin.json.tmpl
        release_webhook_url: "https://spin-plugin-releaser-staging.fermyon.app"

